//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quality.DataAccess.DataFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expertise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expertise()
        {
            this.NoCo = new HashSet<NoCo>();
            this.PAF = new HashSet<PAF>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Commentaire { get; set; }
        public string CQFixed { get; set; }
        public Nullable<decimal> LostWeight { get; set; }
        public int ref_CauseZEId { get; set; }
        public int TicketNC_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoCo> NoCo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAF> PAF { get; set; }
        public virtual ref_CauseZE ref_CauseZE { get; set; }
        public virtual TicketNC TicketNC { get; set; }
    }
}
