//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quality.DataAccess.DataFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public H()
        {
            this.HCQ = new HashSet<HCQ>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string BarCodeUp { get; set; }
        public string BarCodeDown { get; set; }
        public Nullable<int> NkId { get; set; }
        public Nullable<System.DateTime> NkDate { get; set; }
        public int Anomaly_Id { get; set; }
    
        public virtual Anomaly Anomaly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HCQ> HCQ { get; set; }
    }
}
