//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quality.DataAccess.DataFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCQ
    {
        public int Id { get; set; }
        public int HId { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Weight { get; set; }
        public int ref_CQId { get; set; }
    
        public virtual H H { get; set; }
        public virtual ref_CQ ref_CQ { get; set; }
    }
}
