//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quality.DataAccess.DataFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketNC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketNC()
        {
            this.Expertise = new HashSet<Expertise>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int PersonGroupId { get; set; }
        public System.DateTime ManufacturedDate { get; set; }
        public int CQId { get; set; }
        public string Observation { get; set; }
        public decimal Quantity { get; set; }
        public int Order { get; set; }
        public int ref_TypePieceId { get; set; }
        public int ref_UnitId { get; set; }
        public int ref_ProductCodeId { get; set; }
        public int ref_ProductTypeId { get; set; }
        public int Anomaly_Id { get; set; }
        public int Machine_Id { get; set; }
    
        public virtual Anomaly Anomaly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expertise> Expertise { get; set; }
        public virtual ref_Machine ref_Machine { get; set; }
        public virtual ref_ProductCode ref_ProductCode { get; set; }
        public virtual ref_ProductType ref_ProductType { get; set; }
        public virtual ref_TypePiece ref_TypePiece { get; set; }
        public virtual ref_Unit ref_Unit { get; set; }
    }
}
