//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonExpertise
    {
        public int id_expertise { get; set; }
        public string bonNumber { get; set; }
        public int id_expertizer { get; set; }
        public string Observation { get; set; }
        public string CQ_corrige { get; set; }
        public string cause { get; set; }
        public string imputation { get; set; }
        public string ventilation { get; set; }
        public string decision { get; set; }
        public string poids_jete { get; set; }
        public System.DateTime date_expertise { get; set; }
    
        public virtual SaisiePerte SaisiePerte { get; set; }
    }
}
