//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public int id_machine { get; set; }
        public string name { get; set; }
        public Nullable<int> id_guarantor_maintenance { get; set; }
        public bool ARCHIVE { get; set; }
    
        public virtual Personne Personne { get; set; }
    }
}
