//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BASETESTEntities : DbContext
    {
        public BASETESTEntities()
            : base("name=BASETESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atelier> Ateliers { get; set; }
        public virtual DbSet<BonExpertise> BonExpertises { get; set; }
        public virtual DbSet<Critere_CQ> Critere_CQ { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<PosteMachine> PosteMachines { get; set; }
        public virtual DbSet<SaisieChuteCoupeuse> SaisieChuteCoupeuses { get; set; }
        public virtual DbSet<SaisiePerte> SaisiePertes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tCQ_PK> tCQ_PK { get; set; }
        public virtual DbSet<tCQ_UJO> tCQ_UJO { get; set; }
        public virtual DbSet<tFournisseur> tFournisseurs { get; set; }
        public virtual DbSet<tNK> tNKs { get; set; }
        public virtual DbSet<tSaisie_CQ_PK> tSaisie_CQ_PK { get; set; }
        public virtual DbSet<tSaisie_CQ_UJO> tSaisie_CQ_UJO { get; set; }
    }
}
