//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personne()
        {
            this.Machines = new HashSet<Machine>();
            this.Personne1 = new HashSet<Personne>();
            this.Personne11 = new HashSet<Personne>();
            this.SaisiePertes = new HashSet<SaisiePerte>();
        }
    
        public int id_chorus { get; set; }
        public string id_isis { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public Nullable<int> id_department { get; set; }
        public Nullable<int> telephone_number { get; set; }
        public string email { get; set; }
        public bool administrateur { get; set; }
        public Nullable<int> id_Suppleant { get; set; }
        public Nullable<int> IlotID { get; set; }
        public bool ARCHIVE { get; set; }
        public Nullable<int> HierarchiqueID { get; set; }
        public Nullable<System.DateTime> DateArchive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Machine> Machines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personne> Personne1 { get; set; }
        public virtual Personne Personne2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personne> Personne11 { get; set; }
        public virtual Personne Personne3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaisiePerte> SaisiePertes { get; set; }
    }
}
