//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosteMachine
    {
        public int ID { get; set; }
        public string label { get; set; }
        public Nullable<int> AtelierId { get; set; }
        public bool ARCHIVE { get; set; }
        public Nullable<int> BatimentId { get; set; }
    
        public virtual Atelier Atelier { get; set; }
    }
}
