//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaisieChuteCoupeuse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaisieChuteCoupeuse()
        {
            this.tSaisie_CQ_PK = new HashSet<tSaisie_CQ_PK>();
            this.tSaisie_CQ_UJO = new HashSet<tSaisie_CQ_UJO>();
        }
    
        public int id_saisie_chute { get; set; }
        public string ident_coupe { get; set; }
        public string nom_coupe { get; set; }
        public System.DateTime date_saisie { get; set; }
        public string equipe { get; set; }
        public int num_nk { get; set; }
        public string nom_fournisseur { get; set; }
        public System.DateTime date_fab_nk { get; set; }
        public string num_piece { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSaisie_CQ_PK> tSaisie_CQ_PK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSaisie_CQ_UJO> tSaisie_CQ_UJO { get; set; }
    }
}
