//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaisiePerte
    {
        public int id_saisie { get; set; }
        public int id_chorus { get; set; }
        public string id_isis { get; set; }
        public string AgentGroupe { get; set; }
        public string MachineName { get; set; }
        public int id_product { get; set; }
        public string bobineNumber { get; set; }
        public System.DateTime DateFab { get; set; }
        public string bonNumber { get; set; }
        public string typeCQ { get; set; }
        public string TypeProduit { get; set; }
        public Nullable<int> TringleNbr { get; set; }
        public bool TypeRetour { get; set; }
        public string commentaire { get; set; }
        public System.DateTime date_saisie { get; set; }
        public bool receptionZE_status { get; set; }
        public Nullable<System.DateTime> date_ReceptionZE { get; set; }
        public bool expertise_status { get; set; }
    
        public virtual BonExpertise BonExpertise { get; set; }
        public virtual Personne Personne { get; set; }
    }
}
