//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCQ_PK
    {
        public int Id_CQ_PK { get; set; }
        public string Nom_CQ_PK { get; set; }
        public string Libelle_CQ_PK { get; set; }
        public string Type_CQ_PK { get; set; }
    }
}
