//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFournisseur
    {
        public int id_fournisseur { get; set; }
        public string nom_fournisseur { get; set; }
        public string libelle_fournisseur { get; set; }
    }
}
