/*    ==Paramètres de script==

    Version du serveur source : SQL Server 2017 (14.0.1000)
    Édition du moteur de base de données source : Microsoft SQL Server Express Edition
    Type du moteur de base de données source : SQL Server autonome

    Version du serveur cible : SQL Server 2017
    Édition du moteur de base de données cible : Microsoft SQL Server Standard Edition
    Type du moteur de base de données cible : SQL Server autonome
*/
USE [master]
GO
/****** Object:  Database [CStrg]    Script Date: 12/06/2019 13:11:58 ******/
CREATE DATABASE [CStrg]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CStrg', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CStrg.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CStrg_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CStrg_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [CStrg] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CStrg].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CStrg] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CStrg] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CStrg] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CStrg] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CStrg] SET ARITHABORT OFF 
GO
ALTER DATABASE [CStrg] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CStrg] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CStrg] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CStrg] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CStrg] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CStrg] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CStrg] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CStrg] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CStrg] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CStrg] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CStrg] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CStrg] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CStrg] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CStrg] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CStrg] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CStrg] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CStrg] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CStrg] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CStrg] SET  MULTI_USER 
GO
ALTER DATABASE [CStrg] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CStrg] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CStrg] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CStrg] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CStrg] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CStrg] SET QUERY_STORE = OFF
GO
USE [CStrg]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [CStrg]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 12/06/2019 13:11:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[CustomerId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [CStrg] SET  READ_WRITE 
GO
